# Generated by Django 4.2.8 on 2026-03-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('FIREWALL', 'Firewall'), ('WEB_SERVER', 'Web Server'), ('DATABASE', 'Database'), ('APPLICATION', 'Application'), ('NETWORK', 'Network Device')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log_sources',
                'indexes': [models.Index(fields=['source_type'], name='log_sources_source__51c8ec_idx'), models.Index(fields=['is_active'], name='log_sources_is_acti_043f3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('raw_data', models.JSONField()),
                ('parsed', models.BooleanField(default=False)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logs.logsource')),
            ],
            options={
                'db_table': 'logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'log_level'], name='logs_timesta_ce15fd_idx'), models.Index(fields=['source_ip', 'timestamp'], name='logs_source__d92cb8_idx'), models.Index(fields=['event_type', 'timestamp'], name='logs_event_t_b4e06b_idx')],
            },
        ),
    ]
